workflows:
  prod-adhoc:
    name: Production Build - AdHoc Distribution
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.jhutgn.ikl"
        APP_STORE_CONNECT_ISSUER_ID: "c2207f94-c896-4fbd-a76e-25b26298ca95"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "JVPCZS4S58"
        APP_STORE_CONNECT_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYMsfC7gMCEmZclQC
69alM1GOZNHEnQTwgHH9mBz6LKWgCgYIKoZIzj0DAQehRANCAAQCy0fS/Et4Xziv
q3I82Y+iVahtUcyVuYCaKF/F4HWSlxx54Y8eMMlzc8YxL2OsE77gdIkIHaw0wTob
vsBRZAyu
-----END PRIVATE KEY-----"
        CERTIFICATE_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAyif2QopYO3cpp/C/1Vm4Q6OcAb1D4OFTGRq1etoqrqzkmHfp
qVgMpriE4mD941OHcFUJa/6yzk2YnoBwoAo31LF1xgBR4d6LmHpxabeKx5bGbSlN
EV1sLZj12GqQe5nqovMxq5omYBWVb3iF5OLwLe3N8dFdeJqv8d3pZBwvdTIHH6w2
2ewhWkL2IyM5V15aser9jSbkJ+tQ2eFpbOroRy6OOecYhI+nD48JUjxcCLJNpd9+
n13hrgAGHjYS37BHH6en3w/WuxlYBlazbC4QsNhT0nLT+SW8GvO/rjsgM0hNxUn3
7byvhHRzWNOZvGYbmWGM0WZDlZWUT9IPflNvswIDAQABAoIBAAc7wNMGsjuGewYY
VjTjHfXFn+psBEbCqT+HtiCsN8TCSPevqru1e9ZnWdHj2JHOxlTdphWoKmu5WRGq
1NzVIMRKiUVJc6SaWvJcxzwaJiwYGAeF580MQ7ep9noE7iCOFFg6TXevb1oWy58O
d/QFrsRl8u2JKUgMeOk1oIlFfOk7jbnlYKJPRrmVzN9swhUHIyKNTsWkZ8EH1J81
Dz11sCcrHMHE1+z9CcFYzbwzE+8cn5c8xLsTxgi61oLN1ZKg4l3w0XsMu6+Eu2j7
LHF2K+gE8Xs6eDqr1uQHsC/zScPH2U2wBPNwf3/mWXZDPepyKxSoCUzXeJr7gFaz
jrW0HoECgYEA8CScdqHbN43jRrYtcFXqzHAO4QwikF5t7cP4Pq77fEBC1lCN02Lv
U8GXqQBfmP9osnroM8PPW4ZUtI6h8H8vlLOhpP4qN1NLfyqFhC47QbYkykd0GVtb
LRkKFDtkL2OdjrNZFVspnVo1mSHGvtDxomN6oPU4TxMTVbQ804UlPfMCgYEA14E3
3fJtKCYNimSYLCdrBdSknk+LU02FERiQzQTLHHV6vLpXOqtmmnC641JRxp492TDS
ZZ7pxtY+V5qtF7yzPhFIxr24rJZfmEMiy9RQwysUUKW/JJqCOk6YUMTh43wx/zPb
axeaEHvrhHNz5APKVOBpDgsJqZIbs0lj9FSSt0ECgYEAy6D/28ibrpvuIMPR+/Oe
ygQrWcGEfY7VAEywb9bJAS8sfbaIzLqT3h3GkFP0vDO3f8CgrWRYrG9X3FMmFlyC
6ED5zIKJIajL1+UimlbpgGsG/09frzC8O52D4mwKI/UAYUTLQUSwIPGhiVwOvzdF
7kEUdu/483RlbMMM4P+B+OkCgYEAnw+tIJByqRONIvykpNJjV+ZfqsmjWFT7RmcP
WYOUNukvMmWHRLKGBK/4ARkdarAZjllOsdrdSfmQAjEUWVTaJ5GyWZ5m1FwZKtVC
tZd8FNGTKQNtVaMFQ+wG2Ha5E6LzdB3ecej1ufz9FMHyY/W4PXV1lPvoodRJxccB
k7FoqQECgYEAglhcK2+uQQk87ksTnmIW88uQn0M4eLQSMEpWWUZ+90Jf4FDjADuZ
Fj+XKKtUPGOQ/govcuS4Nieh9xF5bVMV7Zj/fOrrFXG8+ZNG71NNkhwOpeqPDtQ7
T0QAkgdhVu1kWh4V5ZYt2jh9y3iP/1XhFwgiG7gGVAk85ADZT+Zbg0o=
-----END RSA PRIVATE KEY-----"
      xcode: latest
      cocoapods: default
    scripts:
      - find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: # You can allow creating resources if existing are not found with `--create` flag
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_ADHOC --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Set up signing certificate
        script:
          xcode-project use-profiles
      - name: Increment build number
        script: agvtool new-version -all $BUILD_NUMBER
      - name: Build ipa for Adhoc
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - 20312915012@cic.du.ac.in