workflows:
  ios-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: c2207f94-c896-4fbd-a76e-25b26298ca95
        APP_STORE_CONNECT_KEY_IDENTIFIER: 8Y52GDJRJD
        APP_STORE_CONNECT_PRIVATE_KEY:  -----BEGIN PRIVATE KEY-----
                                        MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDcTtbYJ0GU8nUEXD
                                        dd2vFqx5+uHg/qMIcHAns0uA7KagCgYIKoZIzj0DAQehRANCAAQXUWpTVcwiZbAK
                                        p847sprrZmP1G8vm92KcShH0MXKshra3P9Xpz6+oA0c18jWFz2y3rTlqtYNJsYaq
                                        S6OgTQ3T
                                        -----END PRIVATE KEY-----
      flutter: 2.10.5
      xcode: '13.0'
      cocoapods: 1.11.3
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "com.jhutgn.ikl" --type IOS_APP_DEVELOPMENT
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - 20312915012@cic.du.ac.in


