workflows:
  ios-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: c2207f94-c896-4fbd-a76e-25b26298ca95
        APP_STORE_CONNECT_KEY_IDENTIFIER: 8Y52GDJRJD
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmlfbElvZ2RMOVdQV3R1V1VNdl85V0tSMl96VlpTcjBHQzRGbnEyVjd3U1U0UFdVSDVJMzBrV0JndnRpRWdKVkljeUg5LTNEd2FaSUpnTTh1ZjBKMDhySjlUWUlPZUR2Z3pFcEFwNGZNRFhiMHpZTzltbV9yWWFPZkdJUVdWS2RfLWtrNVlJaFVnUVFSQlpKVkVXUkIzYmh3bmNrdGJmNDZvY2VTU2o4akNjRkxsNE15N1JHQXZROC1pWUVYZ3RhX1ZlODQyeFVEMUZkdmJGQmF6VVZmbDczaTFxazZlWUNRTXRKTXVtVWtweVd3SF90alhINGV3S0d6OFlBb09SUFUwTE1JaW81VUJram5NODgzemlpR3V5S2x0N2tJUlNWSDBKU3JLQ3hSbkhPd2lvYm9jbUpnclZ3Z29LeTd4T0ZMMnFlbk5nUnBFZVpkdHpkNHBVRXdBMzE4c2dOdTNlZy11NThtU1V1ckU5YjM1T205UTZzWEs0SVZXMnZmM0JFbjEzTnNBYU5RRkVkRzRVR3RKRTdrWVpDcmxkdktYZlNUM3lIRjlvZkVQcUV1bHpzUmNkbEF1VzhxTW9lNDNVUUJreGVadzBIbnFvRVZGMk9WUE0xRVNDT3BhMmZOVVNkRHBzMVhfWl9Ed2hUVUxuVWhEd0JjLURzZ2t0VmFHeDdPSkRHWnRmdmNfSDdEMkJJTThJLV94M0dBUW5nPT0=)
      flutter: 2.10.5
      xcode: '13.0'
      cocoapods: 1.11.3
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "com.jhutgn.ikl" --type IOS_APP_DEVELOPMENT
        --create
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter build ipa --release --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - 20312915012@cic.du.ac.in

