name: ikl
description: A Blup Project.

version: 1.0.0+0

environment:
  sdk: '>=2.7.0 <3.0.0' 

dependencies:
  b_dep:
    path: ../../../GitHub/b_dep
  #    git:
  #      url: https://blupDependenent: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@github.com/BlupGithub/b_dep.git
  #      ref: v1.1096
  cupertino_icons: 1.0.3
  event_bus: 2.0.0
  file_picker: 3.0.3
  file_selector_platform_interface: 2.0.2
  google_fonts: 2.2.0
  image_picker: 0.8.5+3
  intl: 0.17.0
  provider: 4.3.3
  path_provider: 2.0.2
  shared_preferences: 2.0.3
  flutter_screenutil: 5.0.2
  camera: 0.9.8+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

